# Generated by Django 3.2.4 on 2021-06-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchDate', models.DateField()),
                ('homeTeamName', models.CharField(max_length=100)),
                ('homeTeamScore', models.IntegerField(max_length=5)),
                ('awayTeamName', models.CharField(max_length=100)),
                ('awayTeamScore', models.IntegerField(max_length=5)),
                ('score', models.CharField(max_length=100)),
            ],
        ),
    ]
