# Generated by Django 3.2.4 on 2021-06-12 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20210612_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchesdata',
            old_name='score',
            new_name='status',
        ),
    ]
