# Generated by Django 3.2.4 on 2021-06-14 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_rename_score_matchesdata_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='matchesdata',
            table='matchesdata',
        ),
    ]
