# Generated by Django 3.2.4 on 2021-06-14 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_matchesdata_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchesData',
        ),
    ]
