# Generated by Django 3.2.4 on 2021-06-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0005_delete_matchesdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeTeamName', models.CharField(max_length=100)),
                ('homeTeamScore', models.IntegerField()),
                ('awayTeamName', models.CharField(max_length=100)),
                ('awayTeamScore', models.IntegerField()),
                ('matchDate', models.DateField()),
                ('status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'matchesdata',
            },
        ),
    ]
